services:
  postgres:
    image: postgres:17-alpine
    container_name: petagenda_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: petagenda
    ports:
      - "5433:5432"
    volumes:
      - petagenda_pgdata:/var/lib/postgresql/data

volumes:
  petagenda_pgdata:
    driver: local

